server:
  port: 8003
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件路径
  type-aliases-package: com.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: myspringcloud-dept                                 #!!对外暴露的服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: myspringcloud-dept8003
    prefer-ip-address: true #访问路径可以显示
info:
  app.name: demo-myspringcloud
  company.name: www.demo.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
